return {
  "JustasPolis/rose-pine.nvim",
  name = "rose-pine",
  dev = false,
  lazy = false,
  priority = 999,
  opts = {},
  config = function()
    local opts = {
      variant = "main",
      dark_variant = "main",
      dim_inactive_windows = false,
      disable_float_background = true,

      enable = {
        terminal = false,
        legacy_highlights = true, -- Improve compatibility for previous versions of Neovim
        migrations = true, -- Handle deprecated options automatically
      },

      styles = {
        bold = false,
        italic = false,
        transparency = true,
      },

      groups = {
        background = "base",
        background_nc = "_experimental_nc",
        panel = "surface",
        panel_nc = "base",
        border = "highlight_med",
        comment = "muted",
        link = "iris",
        punctuation = "subtle",

        headings = {
          h1 = "iris",
          h2 = "foam",
          h3 = "rose",
          h4 = "gold",
          h5 = "pine",
          h6 = "foam",
        },
      },
      highlight_groups = {
        FloatTitle = { bg = "none", fg = "#908caa" },
        CursorLine = { bg = "#26233a", fg = "none" },
        StatusLine = { fg = "highlight_med", bg = "none", blend = 0 },
        StatusLineNC = { fg = "highlight_med", bg = "none", blend = 0 },
        Search = { bg = "gold", inherit = false },
        PmenuSel = { bg = "none", fg = "iris" },
        GitSignsAdd = { fg = "#5beb82", bg = "none" },
        GitSignsChange = { fg = "rose", bg = "none" },
        GitSignsDelete = { fg = "love", bg = "none" },
        FloatBorder = { bg = "none", fg = "highlight_med" },
        LazyButton = { bg = "none", fg = "#e0def4" },
        LazyH1 = { bg = "none", fg = "#e0def4" },
        LazyButtonActive = { bg = "none", fg = "#e0def4" },
        LazySpecial = { bg = "none", fg = "#e0def4" },
        DiffAdd = { bg = "none", fg = "#5beb82", blend = 0, nocombine = true },
        DiffChange = { bg = "none", fg = "foam", blend = 0, nocombine = true },
        DiffDelete = { bg = "none", fg = "love", blend = 0, nocombine = true },
        DiffText = { bg = "none", fg = "white" },
        GitSignsDeletePreview = { bg = "NONE", fg = "love", blend = 0, nocombine = true },
        GitSignsAddPreview = { bg = "NONE", fg = "#5beb82", blend = 0, nocombine = true },
        GitSignsAddLn = { bg = "NONE", fg = "none", blend = 0, nocombine = true },
        NoiceCmdlinePopupBorderSearch = { bg = "none", fg = "highlight_med" },
        NoiceCmdlineIconSearch = { bg = "none", fg = "#e0def4" },
        NoiceCmdLinePopupTitle = { bg = "none", fg = "#908caa" },
        NoiceCursor = { fg = "text", bg = "highlight_high" },
        NoiceCmdlinePopupBorder = { bg = "none", fg = "highlight_med" },
        NotifyERRORBorder = { fg = "#eb6f92" },
        NotifyWARNBorder = { fg = "#f6c177" },
        NotifyINFOBorder = { fg = "#c4a7e7" },
        NotifyDEBUGBorder = { fg = "#eb6f92" },
        NotifyTRACEBorder = { fg = "#c4a7e7" },
        NotifyINFOTitle = { bg = "none", fg = "#c4a7e7" },
        NotifyINFOIcon = { bg = "none", fg = "#c4a7e7" },
        NotifyWARNTitle = { bg = "none", fg = "#f6c177" },
        NotifyWARNIcon = { bg = "none", fg = "#f6c177" },
        NotifyDEBUGTitle = { bg = "none", fg = "#eb6f92" },
        NotifyDEBUGIcon = { bg = "none", fg = "#eb6f92" },
        NotifyTRACETitle = { bg = "none", fg = "#c4a7e7" },
        NotifyTRACEIcon = { bg = "none", fg = "#c4a7e7" },
        NotifyERRORTitle = { bg = "none", fg = "#eb6f92" },
        NotifyERRORIcon = { bg = "none", fg = "#eb6f92" },
        NoiceVirtualText = { bg = "none", fg = "subtle" },
        NeogitDiffAddHighlight = { bg = "none", fg = "#5beb82" },
        NvimTreeSymlink = { bg = "none", fg = "none", undercurl = false },
        NvimTreeCutHL = { bg = "none", fg = "none", undercurl = false },
        NvimTreeCopiedHL = { bg = "none", fg = "none", undercurl = false },
        NvimTreeExecHL = { bg = "none", fg = "none", undercurl = false },
        NvimTreeDiagnosticInfoFileHL = {
          bg = "none",
          fg = "none",
          undercurl = false,
          underline = false,
        },
        NvimTreeDiagnosticHintFileHL = {
          bg = "none",
          fg = "none",
          undercurl = false,
          underline = false,
        },
        NvimTreeDiagnosticWarnFileHL = {
          bg = "none",
          fg = "none",
          undercurl = false,
          underline = false,
        },
        NvimTreeDiagnosticErrorFileHL = {
          bg = "none",
          fg = "none",
          undercurl = false,
          underline = false,
        },
        NvimTreeLspDiagnosticsInformationText = {
          bg = "none",
          fg = "none",
          undercurl = false,
          underline = false,
        },
        NvimTreeLspDiagnosticsHintText = {
          bg = "none",
          fg = "none",
          undercurl = false,
          underline = false,
        },
        NvimTreeLspDiagnosticsWarningText = {
          bg = "none",
          fg = "none",
          undercurl = false,
          underline = false,
        },
        NvimTreeExecFile = { bg = "none", fg = "none", undercurl = false, underline = false },
        NvimTreeBookmarkHL = { bg = "none", fg = "none", undercurl = false, underline = false },
        BufferLineBackground = { bg = "none", fg = "none", undercurl = false, underline = false, bold = false },
        BufferLineSeparator = { bg = "none", fg = "none", undercurl = false, underline = false, bold = false },
        BufferLineBuffer = { bg = "none", undercurl = false, underline = false, bold = false },
        BufferLineNumbers = { bg = "none", undercurl = false, underline = false, bold = false },
        BufferLineTabSeparator = { bg = "none", fg = "none", undercurl = false, underline = false },
        BufferLineFill = { bg = "none", fg = "none", undercurl = false, underline = false },

        NoiceLspProgressClient = { fg = "#908caa", bg = "none" },
        NoiceLspProgressSpinner = { fg = "#908caa", bg = "none" },
        NoiceLspProgressTitle = { fg = "#908caa", bg = "none" },
      },
    }
    require("rose-pine").setup(opts)

    vim.cmd("colorscheme rose-pine")
  end,
}
