live_config_reload = true

[colors.bright]
black = "0x6e6a86"
blue = "0x9ccfd8"
cyan = "0xebbcba"
green = "0x31748f"
magenta = "0xc4a7e7"
red = "0xeb6f92"
white = "0xe0def4"
yellow = "0xf6c177"

[colors.cursor]
cursor = "0x524f67"
text = "0xFFFFFF"

[colors.hints.end]
background = "#1f1d2e"
foreground = "#6e6a86"

[colors.hints.start]
background = "#1f1d2e"
foreground = "#908caa"

[colors.line_indicator]
background = "None"
foreground = "None"

[colors.normal]
black = "0x26233a"
blue = "0x9ccfd8"
cyan = "0xebbcba"
green = "0x31748f"
magenta = "0xc4a7e7"
red = "0xeb6f92"
white = "0xe0def4"
yellow = "0xf6c177"

[colors.primary]
background = "0x191724"
foreground = "0xFFFFFF"

[colors.selection]
background = "0x403d52"
text = "0xe0def4"

[colors.vi_mode_cursor]
cursor = "0x524f67"
text = "0xe0def4"

[cursor]
style = "Block"

[font]
size = 15

[font.normal]
family = "JetbrainsMono Nerd Font"
style = "SemiBold"

[mouse]
hide_when_typing = true

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[shell]
program = "/run/current-system/sw/bin/fish"

[window]
decorations = "buttonless"
dynamic_padding = true
opacity = 0.9
startup_mode = "Windowed"

[window.padding]
x = 4
y = 0
