format = """
$directory\
$git_branch\
$git_status\
$jobs\
$character\
"""

add_newline = false

[directory]
truncate_to_repo = false
read_only = ''
truncation_symbol = '…/'
style = "cyan"

[git_branch]
format = '[$symbol$branch]($style) '
symbol = ''
style = '#c4a7e7'

[cmd_duration]
format = ''

[character]
success_symbol = '[❯](purple)'
error_symbol = '[❯](purple)'

[package]
disabled = true

[jobs]
symbol = ''
style = 'red'

[git_status]
modified = "✘"
format = '[$all_status$ahead_behind]($style) '
style = 'red'
